apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: centralidp
spec:
  destination:
    namespace: product-portal
    name: in-cluster
  source:
    path: charts/centralidp
    repoURL: 'https://github.com/eclipse-tractusx/portal-iam.git'
    targetRevision: v1.2.0
    plugin:
      env:
        - name: AVP_SECRET
          value: vault-secret
        - name: helm_args
          value: '-f values.yaml -f ../../consortia/environments/centralidp/values-stable.yaml'
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  project: project-portal
